#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#Load common configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zlogin" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zlogin"
fi
