#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#Load common configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zlogout" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zlogout"
fi
