#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#
#Load common configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile"
fi

# Tab completion
# Directories
export WORK="/afs/cern.ch/work/d/dabernin/private"
export EOS="/eos/user/d/dabernin"
export EOSSCIFI="/eos/lhcb/testbeam/scifi"
export DATA="/eos/user/d/dabernin/DATA"

# Make own software available
export PATH="$WORK/bin:$PATH"
export LD_LIBRARY_PATH="$WORK/lib:$WORK/lib64:$LD_LIBRARY_PATH"
export CPATH="$WORK/include:$CPATH"

